TEMPERATURE: 1.1
GLUE_TYPES: ['A', 'B', 'C', 'D']
GLUE_INTERACTION:
  - [4.0, 4.0, 4.0, 4.0]
  - [1.0, 1.0, 1.0, 1.0]
  - [0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0]
GLUE_BINDING_TO_FREE: {'A': -0.0, 'B': -0.0, 'C': 0.0, 'D': 0.0}
chem_potentials: {"Seed": 0.0, "T1": 0.0}
colorMap: {"Seed": "red", "T1": "green"}
tiles:
  - {north: 'A', east: 'A', south: 'A', west: 'A', name: 'Seed'}
  - {north: 'A', east: 'A', south: 'A', west: 'A', name: 'T1'}
