TEMPERATURE: 0.005
GLUE_TYPES: ['A', 'B', 'C', 'D']
GLUE_INTERACTION:
  - [5.0, 1.0, 0.0, 0.0]
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0]
GLUE_BINDING_TO_FREE: {'A': -0.0, 'B': -0.0, 'C': 0.0, 'D': 0.0}
chem_potentials: {"Seed": 0.0, "T1": 0.0, "T2": 0.0}
colorMap: {"Seed": "red", "T1": "green", "T2": "blue"}
tiles:
  - {north: 'A', east: 'B', south: 'A', west: 'A', name: 'Seed'}
  - {north: 'A', east: 'B', south: 'A', west: 'B', name: 'T1'}
